apps/authentication/urls.py
from django.urls import path

from . import views
from .views import register_org

urlpatterns = [
    path('', views.signin, name='login'),
    path('login/', views.signin, name="login"),
    path('register/', views.signup, name="register"),
    path('logout/', views.signout, name="logout"),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('password_reset_confirm/<uidb64>/<token>/', views.password_reset_confirm, name='password_reset_confirm'),
    path("full_register/", views.register_user_full, name="full_register"),
    path("register_org/", register_org, name="register_org"),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
]

cajulab_remote_sensing_dashboard/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from apps.dashboard import views

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('apps.authentication.urls'), name='Authentication'),
    path('dashboard/', include('apps.dashboard.urls'), name='Dashboard'),
)

urlpatterns += static(settings.STATIC_URL)

handler400 = views.error_400
handler403 = views.error_403
handler404 = views.error_404
handler500 = views.error_500

apps/authentication/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2020 - Technoserve
"""

from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.db.models.signals import post_save


# Create your models here.

class RemOrganization(models.Model):
    class Status:
        ACTIVE = 1
        INACTIVE = 0

    ACTIVE = 1
    INACTIVE = 0
    Status = [
        (ACTIVE, 'Active'),
        (INACTIVE, 'Inactive'),
    ]

    # id = models.BigAutoField(primary_key=True)
    organization_name = models.CharField(max_length=200, unique=True)
    description = models.CharField(max_length=200)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone = models.CharField(validators=[phone_regex], max_length=17, blank=True)  # validators should be a list
    # phone = PhoneNumberField(null=False, blank=False, unique=True)
    e_mail = models.EmailField(max_length=254)
    website = models.URLField(max_length=254, null=False)
    address = models.CharField(max_length=200)
    country = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    status = models.IntegerField(choices=Status, default=ACTIVE, )
    created_by = models.BigIntegerField(null=True)
    created_date = models.DateTimeField(blank=True, null=True)
    updated_by = models.BigIntegerField(null=True)
    updated_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.organization_name


class RemRole(models.Model):
    class Status():
        ACTIVE = 1
        INACTIVE = 0

    ACTIVE = 1
    INACTIVE = 0
    Status = [
        (ACTIVE, 'Active'),
        (INACTIVE, 'Inactive'),
    ]
    # id = models.BigAutoField(primary_key=True)
    role_name = models.CharField(max_length=200)
    # organization = models.ForeignKey(RemOrganization, on_delete=models.CASCADE, null=True)
    status = models.IntegerField(choices=Status, default=ACTIVE, )
    created_by = models.BigIntegerField(null=True)
    created_date = models.DateTimeField(blank=True, null=True)
    updated_by = models.BigIntegerField(null=True)
    updated_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.role_name


class RemUserManager(models.Manager):
    pass


class RemUser(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    email = models.CharField(max_length=64, blank=True)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number must be entered in the format: '+999999999'. Up to 15 digits "
                                         "allowed.")
    phone = models.CharField(validators=[phone_regex], max_length=17, blank=True)
    organization = models.ForeignKey(RemOrganization, on_delete=models.CASCADE, null=True, blank=True)
    role = models.ForeignKey(RemRole, on_delete=models.CASCADE, null=True)
    objects = RemUserManager()

    def __str__(self):
        return self.user.username


def create_remuser(sender, **kwargs):
    if kwargs['created']:
        rem_user = RemUser.objects.create(user=kwargs['instance'])


post_save.connect(create_remuser, sender=User)

apps/authentication/views.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2021 - present Technoserve x Damilola
"""

import datetime
import logging
import os

from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.http import HttpResponse
# Create your views here.
from django.shortcuts import render, redirect
from django.template import loader
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.translation import gettext

from . import forms as custom_forms
from .forms import *
from .forms import SignUpForm, LoginForm
from .models import RemUser
from .utils import account_activation_token

logger = logging.getLogger(__name__)


def signin(request):
    msg = None
    if request.user.is_authenticated:
        return redirect("/dashboard/")

    elif request.method == "POST":
        form = LoginForm(data=request.POST or None)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            remember_me = form.cleaned_data.get("remember_me")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                if remember_me:
                    request.session.set_expiry(604800)
                return redirect("/dashboard/")
            else:
                msg = gettext('Invalid credentials')

        else:
            msg = str(form.errors)  # 'Error validating the form'
    else:
        form = LoginForm()

    return render(request, "authentication/login.html", {"form": form, "msg": msg, 'segment': 'login'})


def signup(request):
    msg = None
    success = False
    fullpage = not (request.user.is_staff or request.user.is_superuser)

    try:
        if request.method == 'POST':
            form = SignUpForm(request.POST)
            if form.is_valid():
                user = form.save(commit=False)
                user.is_active = False

                email = form.cleaned_data.get("email")
                phone = form.cleaned_data.get("phone")
                organization = form.cleaned_data.get("organization")
                role = form.cleaned_data.get("role")

                user.save()

                rem_user = RemUser.objects.get(user=user)

                current_site = get_current_site(request)
                mail_subject = gettext(
                    'Activate your Cashew Remote Sensing account.')
                message = loader.get_template('authentication/acc_active_email.html').render(
                    {
                        'user': user,
                        'domain': current_site.domain,
                        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                        'token': account_activation_token.make_token(user),
                    }
                )
                to_email = user.email
                email = EmailMessage(
                    mail_subject,
                    message,
                    from_email='"Caju-Lab Support" <' +
                               os.getenv("EMAIL_HOST_USER") + '>',
                    to=[to_email]
                )
                email.content_subtype = "html"

                email.send()

                msg = gettext(
                    'Please confirm your email address to complete the registration')
                success = True
                rem_user.email = email
                rem_user.phone = phone
                rem_user.organization = organization
                rem_user.role = role
                rem_user.save()

            else:
                msg = gettext('Form is not valid')
        else:
            form = SignUpForm()
        return render(request, 'authentication/register.html',
                      {"form": form, "msg": msg, "success": success, "fullpage": fullpage})

    except Exception as e:
        print(e)
        msg = gettext('An Error has Occurred')
        return render(request, 'authentication/register.html',
                      {"form": form, "msg": msg, "success": False, "fullpage": fullpage})


@login_required(login_url="/")
def register_org(request):
    msg = None
    success = False

    if request.method == "POST":
        form = RegisterOrganization(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            try:
                current_user = request.user
                if current_user.is_authenticated:
                    # Do something for authenticated users.
                    obj.created_by = current_user.id
                    obj.created_date = datetime.datetime.now()
                    obj.updated_by = current_user.id
                    obj.updated_date = datetime.datetime.now()

                    # return redirect("/login/")
            except Exception:
                pass
            obj.save()
            msg = gettext(
                'Organization created - please <a href="/register">register user</a>.')
            success = True

        else:
            msg = gettext('Form is not valid')
    else:
        form = RegisterOrganization()

    return render(request, "authentication/register_org.html", {"form": form, "msg": msg, "success": success})


def register_user_full(request):
    msg = None
    success = False

    if request.method == "POST":
        form = FullSignUpForm(request.POST)
        if form.is_valid():

            raw_password1 = form.cleaned_data.get("password1")
            raw_password2 = form.cleaned_data.get("password2")

            if raw_password1 == raw_password2:
                current_user = request.user
                # id = uuid.uuid4().int
                obj = form.save(commit=False)
                obj.created_by = current_user.id
                obj.created_date = datetime.datetime.now()
                obj.updated_by = current_user.id
                obj.updated_date = datetime.datetime.now()

                org_name = form.cleaned_data.get("organization_name")
                obj.organization = org_name

                email = form.cleaned_data.get("email")
                obj.e_mail = email

                # obj.id = id

                obj.password = raw_password1

                obj.save()
                # username = form.cleaned_data.get("username")
                # raw_password = form.cleaned_data.get("password1")
                # user = authenticate(username=username, password=raw_password)

                user_name = form.cleaned_data.get("user_name")
                email = form.cleaned_data.get("email")

                sec_user = User(username=user_name, email=email)
                sec_user.set_password(raw_password1)

                sec_user.save()

                msg = 'User created - please <a href="/login">login</a>.'
                success = True

                # return redirect("/login/")

            else:
                msg = gettext('Form is not valid - Passwords do not match')

        else:
            msg = gettext('Form is not valid')
    else:
        form = FullSignUpForm()

    return render(request, "authentication/full_login.html", {"form": form, "msg": msg, "success": success})


def signout(request):
    logout(request)
    msg = None

    if request.method == "POST":
        form = LoginForm(data=request.POST or None)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            remember_me = form.cleaned_data.get("remember_me")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                if remember_me:
                    request.session.set_expiry(604800)
                return redirect("/")
            else:
                msg = gettext('Invalid credentials')

        else:
            msg = str(form.errors)  # 'Error validating the form'
    else:

        form = LoginForm()

    return render(request, "authentication/login.html", {"form": form, "msg": msg, 'segment': 'login'})


def forgot_password(request):
    msg = None
    success = False

    if request.method == 'POST':
        form = custom_forms.ForgotPassword(request.POST)
        if form.is_valid():

            email = form.cleaned_data['email']
            user = User.objects.get(email=email)

            current_site = get_current_site(request)
            mail_subject = gettext('Reset your Password')
            message = loader.get_template('authentication/password_reset_email.html').render(
                {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': account_activation_token.make_token(user),
                }
            )
            # message = render_to_string('authentication/acc_active_email.html', {
            #     'user': user,
            #     'domain': current_site.domain,
            #     'uid':urlsafe_base64_encode(force_bytes(user.pk)),
            #     'token':account_activation_token.make_token(user),
            # })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject,
                message,
                from_email='"Caju-Lab Support" <cajusupport@tnslabs.org>',
                to=[to_email]
            )

apps/templates/authentication/email_confirm_invalid.html
{% extends 'layouts/base-fullscreen.html' %}
{% load i18n %}

{% block title %} Error 403 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- Page content -->
    <div class="container mt--8 pb-5">
      <div class="row justify-content-center">
        <div class="col-lg-5 col-md-7">
          <div class="card bg-secondary shadow border-0">
            <div class="card-header bg-transparent pb-5">

              <div class="text-muted text-center mt-2 mb-3">
               {% trans " Ooops activation link is invalid!" %}      
              </div>

              <div class="text-center mb-4">
                {% trans "Please reach out to us through this" %} <a class="text-primary" href="https://www.technoserve.org/contact-us/">{% trans "link" %}</a>.
              </div>

            </div>
          </div>
          <div class="row mt-3">
            <div class="col-6">
              <a href="/" class="text-light"><small>{% trans "Home" %}</small></a>
            </div>          
            <div class="col-6 text-right">
              <a target="_blank" href="https://www.technoserve.org/contact-us/" class="text-light"><small>{% trans "Contact Us" %}</small></a>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

apps/templates/authentication/email_confirmed.html
{% extends 'layouts/base-fullscreen.html' %}
{% load i18n %}

{% block title %} Error 403 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- Page content -->
    <div class="container mt--8 pb-5">
      <div class="row justify-content-center">
        <div class="col-lg-5 col-md-7">
          <div class="card bg-secondary shadow border-0">
            <div class="card-header bg-transparent pb-5">

              <div class="text-muted text-center mt-2 mb-3">
                {% trans "Thank you for your email confirmation." %}      
              </div>

              <div class="text-center mb-4">
                {% trans "Now you can" %} <a class="text-primary" href="{% url 'login' %}">{% trans "login" %}</a> {% trans "your account" %}.
              </div>

            </div>
          </div>
          <div class="row mt-3">
            <div class="col-6">
              <a href="/" class="text-light"><small>{% trans "Home" %}</small></a>
            </div>          
            <div class="col-6 text-right">
              <a target="_blank" href="https://www.technoserve.org/contact-us/" class="text-light"><small>{% trans "Contact Us" %}</small></a>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

apps/templates/authentication/full_login.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Register {% endblock title %}

{% load i18n %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- Page content -->
    <div class="container mt--8 pb-5">
      <!-- Table -->
      <div class="row justify-content-center">
        <div class="col-lg-6 col-md-8">
        
          <div class="card bg-secondary shadow border-0">
            <div class="card-header bg-transparent pb-5">
              <div class="text-muted text-center mt-2 mb-4">
                {% trans "Sign Up" %}
              </div>
            </div>
            <div class="card-body px-lg-5 py-lg-5">
              <div class="text-center text-muted mb-4">

                {% if msg %}
                  <small>{{ msg | safe }}</small>
                {% else %}
                  {% trans "Add your credentials" %}
                {% endif %}  
              
              </div>

              {% if not success %}

                <form method="POST" id="personForm" roles-url="{% url 'load_roles' %}">

                  {% csrf_token %}
            
                  <div class="form-group">
                    <div class="input-group input-group-alternative mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text"><i class="ni ni-hat-3"></i></span>
                      </div>
                      {{ form.user_name }}
                    </div>
                  </div>
                  <span class="text-error">{{ form.user_name.errors }}</span>

                  <div class="form-group">
                    <div class="input-group input-group-alternative mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text"><i class="ni ni-hat-3"></i></span>
                      </div>
                      {{ form.first_name }}
                    </div>
                  </div>
                  <span class="text-error">{{ form.first_name.errors }}</span>

                  <div class="form-group">
                    <div class="input-group input-group-alternative mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text"><i class="ni ni-hat-3"></i></span>
                      </div>
                      {{ form.last_name }}
                    </div>
                  </div>
                  <span class="text-error">{{ form.last_name.errors }}</span>

                  <div class="form-group">
                    <div class="input-group input-group-alternative mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text"><i class="ni ni-hat-3"></i></span>
                      </div>
                      <div class="input-group-prepend">
                        <span class="input-group-text">{% trans "Gender:" %}</i></span>
                      </div>
                      {{ form.gender }}
                    </div>
                  </div>
                  <span class="text-error">{{ form.gender.errors }}</span>

                  <div class="form-group">
                    <div class="input-group input-group-alternative mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text"><i class="ni ni-hat-3"></i></span>
                      </div>
                      <div class="input-group-prepend">
                        <span class="input-group-text">{% trans "Date of Birth:" %}</i></span>
                      </div>
                        {{ form.date_of_birth }}
                    </div>
                  </div>
                  <span class="text-error">{{ form.date_of_birth.errors }}</span>

                  <div class="form-group">
                    <div class="input-group input-group-alternative mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text"><i class="ni ni-hat-3"></i></span>
                      </div>
                      {{ form.phone }}
                    </div>
                  </div>
                  <span class="text-error">{{ form.phone.errors }}</span>

                  <div class="form-group">
                    <div class="input-group input-group-alternative mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text"><i class="ni ni-email-83"></i></span>
                      </div>
                      {{ form.email }}
                    </div>
                  </div>
                  <span class="text-error">{{ form.email.errors }}</span>

                  <div class="form-group">
                    <div class="input-group input-group-alternative mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text"><i class="ni ni-email-83"></i></span>
                      </div>
                      <div class="input-group-prepend">
                        <span class="input-group-text">{% trans "Organization Name:" %}</i></span>
                      </div>
                      {{ form.organization_name }}
                    </div>
                  </div>
                  <span class="text-error">{{ form.organization_name.errors }}</span>

                  <div class="form-group">
                    <div class="input-group input-group-alternative mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text"><i class="ni ni-email-83"></i></span>
                      </div>
                      <div class="input-group-prepend">
                        <span class="input-group-text">{% trans "Role:" %}</i></span>
                      </div>
                      {{ form.role }}
                    </div>
                  </div>
                  <span class="text-error">{{ form.role.errors }}</span>

                  <div class="form-group">
                    <div class="input-group input-group-alternative mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text"><i class="ni ni-email-83"></i></span>
                      </div>
                      {{ form.address }}
                    </div>
                  </div>
                  <span class="text-error">{{ form.address.errors }}</span>

                  <div class="form-group">
                    <div class="input-group input-group-alternative mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text"><i class="ni ni-email-83"></i></span>
                      </div>
                      {{ form.country }}
                    </div>
                  </div>
                  <span class="text-error">{{ form.country.errors }}</span>

                  <div class="form-group">
                    <div class="input-group input-group-alternative mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text"><i class="ni ni-email-83"></i></span>
                      </div>
                      {{ form.city }}
                    </div>
                  </div>
                  <span class="text-error">{{ form.city.errors }}</span>

                  <div class="form-group">
                    <div class="input-group input-group-alternative">
                      <div class="input-group-prepend">
                        <span class="input-group-text"><i class="ni ni-lock-circle-open"></i></span>
                      </div>
                      {{ form.password1 }}
                    </div>
                  </div>
                  <span class="text-error">{{ form.password1.errors }}</span>

                  <div class="form-group">
                    <div class="input-group input-group-alternative">
                      <div class="input-group-prepend">
                        <span class="input-group-text"><i class="ni ni-lock-circle-open"></i></span>
                      </div>
                      {{ form.password2 }}
                    </div>
                  </div>
                  <span class="text-error">{{ form.password2.errors }}</span>

                  <div class="row my-4">
                    <div class="col-12">
                      <div class="custom-control custom-control-alternative custom-checkbox">
                        <input class="custom-control-input" id="customCheckRegister" type="checkbox">
                        <label class="custom-control-label" for="customCheckRegister">
                          <span class="text-muted">I agree with the <a href="#!">{% trans "Privacy Policy" %}</a></span>
                        </label>
                      </div>
                    </div>
                  </div>
                  <div class="text-center">
                    <button type="submit" class="btn btn-primary mt-4">{% trans "Create account" %}</button>
                  </div>
                </form>

              {% endif %}  
  
            </div>
          </div>

        </div>
      </div>

      <div class="row mt-3">
        <div class="col-3"></div>
        <div class="col-3">
          <a href="{% url 'login' %}" class="text-light"><small>{% trans "Login" %}</small></a>
        </div>
        <div class="col-3 text-right">
          <a href="https://www.technoserve.org/contact-us/" class="text-light"><small>{% trans "Contact Us" %}</small></a>
        </div>
      </div>

    </div>
  </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}

<script>
  $("#id_organization").change(function () {
    var url = $("#personForm").attr("roles-url");
    var orgId = $(this).val();

    $.ajax({
      url: url,
      data: {
        'organization_name': orgId
      },
      success: function (data) {
        $("#id_role").html(data);
      }
    });

  });
</script>

{% endblock javascripts %}


apps/templates/authentication/login.html
{% extends 'layouts/base-fullscreen.html' %}

{% load i18n %}

{% block title %} Login {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

{% csrf_token %}

    <!-- Page content -->
    <div class="container mt--8 pb-5">
      <div class="row justify-content-center">
        <div class="col-lg-5 col-md-7">
          <div class="card bg-secondary shadow border-0">
            <div class="card-header bg-transparent pb-5">
              <div class="text-muted text-center mt-2 mb-3">
                {% trans "Sign In" %}
              </div>
            </div>
            <div class="card-body px-lg-5 py-lg-5">
              <div class="text-center text-muted mb-4">

                {% if msg %}
                  <p>{{ msg }}</p>
                {% else %}
                  <p>
                    {% trans "Add your credentials" %}
                  </p>
                {% endif %}

              </div>

              <form method="POST">

                {% csrf_token %}

                <div class="form-group mb-3">
                  <div class="input-group input-group-alternative">
                    <div class="input-group-prepend">
                      <span class="input-group-text"><i class="ni ni-hat-3"></i></span>
                    </div>
                    {{ form.username }}
                  </div>
                </div>

                <div class="form-group">
                  <div class="input-group input-group-alternative">
                    <div class="input-group-prepend">
                      <span class="input-group-text"><i class="ni ni-lock-circle-open"></i></span>
                    </div>
                    {{ form.password }}
                  </div>
                </div>

                <div class="custom-control custom-control-alternative custom-checkbox">
                  <input class="custom-control-input" id=" customCheckLogin" type="checkbox" name = "remember_me">
                  <label class="custom-control-label" for=" customCheckLogin">
                    <span class="text-muted">{% trans "Remember me" %}</span>
                  </label>
                </div>
                <div class="text-center">
                  <button type="submit" class="btn btn-secondary my-4">{% trans "Sign in" %}</button>
                </div>
{#                <div class="text-center">#}
{#                  <a href="{% url 'forgot_password' %}" class="text-muted"><small><u>{% trans "Forgot password" %}</u></small></a>#}
{#                </div>#}
              </form>
            </div>
          </div>
          <div class="row mt-3">
            <div class="col-6">
              <a href="{% url 'register' %}" class="text-light"><small>{% trans "Register" %}</small></a>
            </div>
            <div class="col-6 text-right">
              <a href="https://www.technoserve.org/contact-us/" class="text-light"><small>{% trans "Contact Us" %}</small></a>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}